sudo: required
services:
  - docker

before_install:
  - docker build -t hank9653/docker-react -f Dockerfile.dev .

script:
  - docker run -t hank9653/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:
    - FIXME
  app: "docker"
  env: "Docker-env"
  bucket_name: "FIXME"
  bucket_path: "docker"
  on:
    - branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"